# Generated by Django 2.1 on 2018-09-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_opinionpoll_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='poll',
        ),
        migrations.DeleteModel(
            name='OpinionPoll',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
