# Generated by Django 2.1 on 2018-09-09 06:42

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainform',
            name='dustbin',
            field=models.CharField(choices=[('Sadar', 'Sadar'), ('Russell', 'Russell'), ('Reliance', 'Reliance')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complainform',
            name='subject',
            field=models.CharField(default=datetime.datetime(2018, 9, 9, 6, 42, 5, 794570, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
